### ISSUE TITLE
Bug with magic method on version 5.6

### ISSUE THREAD

**Issue by osadchyi-s** [pdffiller/pdffiller-php-api-client#15]
[Для магічного метода __set](https://github.com/pdffiller/pdffiller-php-api-client/blob/master/src/Core/Model.php#L454)  у випадку присвоєння окремого ключа масива викидає помилку

> Indirect modification of overloaded property 

Наприклад, example для темплейтів видаватиме помилку:
```
$fillableTemplate->fillable_fields['Text_1'] = 'Hop hey lalaley';
$fillableTemplate->fillable_fields['Number_1'] = '2016';
$fillableTemplate->fillable_fields['Checkbox_1'] = '1';
$fillableTemplate->fillable_fields['Date_1'] = '03/07/2016';
```
Якщо замінити на одне присвоєння, то проблема зникає:
```
$fillableTemplate->fillable_fields = [
    'Text_1' => 'Hop hey lalaley',
    'Number_1' => '2016',
    'Checkbox_1' => '1',
    'Date_1' => '03/07/2016',
];
```
Проблема виявлена на php 5.6
На Хабрахабрі щось схоже нагуглив: https://habrahabr.ru/post/103834/

**Comment by srgkas** [comment]
Хорошее замечание. На самом дела ошибка появляется из-за того, что массив, который мы заполняем с помощью магического метода неинициализирован. Исправить проблему можно, добавив строку
`$fillableTemplate->fillable_fields = [];`
перед заполнением массива. Позже я сделаю фикс в коде клиента.

**Comment by srgkas** [comment]
#26
