### ISSUE TITLE
Убрать ненужные зависимости

### ISSUE THREAD

**Issue by aslikeyou** [pdffiller/pdffiller-php-api-client#22]
Сейчас клиент использует следующие библиотеки:

- illuminate/validation
- public-rest-api-validation-rules

Мы будем отказываться от public-rest-api-validation-rules, а illuminate/validation накладывает ограничение на версию. Нужно сделать так, что бы эти библиотеки не использовались.

**Comment by RDSergij** [comment]
#23

**Comment by RDSergij** [comment]
#23
